### ISSUE TITLE
Problem following introduction

### ISSUE THREAD

**Issue by awcoding** [sematext/solr-autocomplete#2]
I followed this guide:
https://sematext.com/blog/2017/03/20/sematext-solr-autocomplete-introduction-and-howto/
but I had problems at the core creation step. The guide left out which files to grab, so I copied solr-autocomplete/example/solr/collection1. This is the error I received:

```shell
solr-6.3.0$ bin/solr create -c autocomplete -d ./server/solr/collection1/conf/

Connecting to ZooKeeper at localhost:9983 ...
Uploading /home/aw/Downloads/solr-6.3.0/server/solr/collection1/conf for config autocomplete to ZooKeeper at localhost:9983

Creating new collection 'autocomplete' using command:
http://localhost:8983/solr/admin/collections?action=CREATE&name=autocomplete&numShards=1&replicationFactor=1&maxShardsPerNode=1&collection.configName=autocomplete

ERROR: Failed to create collection 'autocomplete' due to: {10.1.1.53:8983_solr=org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://10.1.1.53:8983/solr: Error CREATEing SolrCore 'autocomplete_shard1_replica1': Unable to create core [autocomplete_shard1_replica1] Caused by: org.apache.solr.handler.dataimport.DataImportHandler}
```

It's also unclear also where to get the schema.xml file from, since one doesn't appear to exist in this project. I tried renaming schema-function-query-ordering.xml to schema.xml and there was no change to the error above. I also obtained this error with solr-6.4.0. before I downgraded to solr-6.3.0 to see if that would make a difference. It didn't. Please advise.

**Comment by radu-gheorghe** [comment]
You should be good with using the `solr/collection1/conf/` directory from the `solr-autocomplete` clone. I've updated the guide to make that clear, sorry for being vague there.

**Comment by awcoding** [comment]
Your guide doesn't work. Have you tried it yourself from a fresh install?

I also tried adding in a data-config.xml file (it's not in collection1/conf) that mirrors the one in the readme but that didn't help either.

**Comment by radu-gheorghe** [comment]
I did try it from a fresh install to write down the commands for the blog post. I will check it again, maybe I've been missing something.

**Comment by radu-gheorghe** [comment]
It looks like I did a major oopsie on this one, sorry for that. I forgot that I made some changes and was under the impression that I had a clean install.

The error you saw is likely because it misses the DataImportHandler class (you'd see that in the log), which in turn is because the sample solrconfig.xml doesn't load the jar that contains it.

Also, the example configuration that's meant to be used is in `example/solr/collection1/conf` (note the addition of `example` there) which has a sample data-config.xml, too (though we're not using it in this tutorial - it would need a few tweaks to be fully functional, depending on how you'd have your source core/collection).

Anyway, if you clone the repo again or update it, then follow the tutorial, it should work. Please let me know if you hit any more issues, I'm closing this one for now.
